# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
name: postgresql
version: 1.2.0
icon: https://www.postgresql.org/media/img/about/press/elephant.png
appVersion: 12.3.0
description: PostgreSQL deployment based on Bitnami, embedded for use alongside Iris deployment
keywords:
  - db
  - postgresql
